container:
  dockerfile: Dockerfile
  cpu: 8
  memory: 24G
  
repo_task:
  script:
   - cd ~/android/lineage
   - repo init -u https://github.com/LineageOS/android.git -b lineage-16.0;
   - repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)

build_task:
  timeout_in: 120m
  depends_on: repo
  
  script:
    - cd ~/android/lineage
    - source build/envsetup.sh; breakfast lavender; croot; brunch lavender
