  
task:
  container:
    dockerfile: Dockerfile
    cpu: 8
    memory: 16G

  lineage_cache:
    folder: $HOME/android/lineage

  build_script:
    - cd $HOME/android/lineage; chmod a+x $HOME/build.sh; $HOME/build.sh
