container:
  image: ubuntu:latest
  cpu: 8
  memory: 16G
  
build_task:
  update_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -yq install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3
    
  setup_platform_tools_script:
    - cd $HOME
    - curl -q -L -O 'https://dl.google.com/android/repository/platform-tools-latest-linux.zip'
    - unzip -q platform-tools-latest-linux.zip -d ~
 
  repo_init_script:
    - mkdir -p ~/bin
    - mkdir -p ~/android/lineage
    - curl -q https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo
    - PATH="$HOME/bin:$HOME/platform-tools:$PATH"
    - git config --global user.email "buildbot@docker.dock"
    - git config --global user.name "LineageOS Buildbot"
    - cd ~/android/lineage
    - repo init -u https://github.com/LineageOS/android.git -b lineage-16.0
  
  repo_sync_script:
    - repo sync -c -j8 --no-tags --no-clone-bundle
